<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create(['code'=>'AFG','name'=>	'Afganistán']);
        Country::create(['code'=>'ALA','name'=>	'Islas Åland']);
        Country::create(['code'=>'ALB','name'=>	'Albania']);
        Country::create(['code'=>'DEU','name'=>	'Alemania']);
        Country::create(['code'=>'AND','name'=>	'Andorra']);
        Country::create(['code'=>'AGO','name'=>	'Angola']);
        Country::create(['code'=>'AIA','name'=>	'Anguila']);
        Country::create(['code'=>'ATA','name'=>	'Antártida']);
        Country::create(['code'=>'ATG','name'=>	'Antigua y Barbuda']);
        Country::create(['code'=>'SAU','name'=>	'Arabia Saudita']);
        Country::create(['code'=>'DZA','name'=>	'Argelia']);
        Country::create(['code'=>'ARG','name'=>	'Argentina']);
        Country::create(['code'=>'ARM','name'=>	'Armenia']);
        Country::create(['code'=>'ABW','name'=>	'Aruba']);
        Country::create(['code'=>'AUS','name'=>	'Australia']);
        Country::create(['code'=>'AUT','name'=>	'Austria']);
        Country::create(['code'=>'AZE','name'=>	'Azerbaiyán']);
        Country::create(['code'=>'BHS','name'=>	'Bahamas (las)']);
        Country::create(['code'=>'BGD','name'=>	'Bangladés']);
        Country::create(['code'=>'BRB','name'=>	'Barbados']);
        Country::create(['code'=>'BHR','name'=>	'Baréin']);
        Country::create(['code'=>'BEL','name'=>	'Bélgica']);
        Country::create(['code'=>'BLZ','name'=>	'Belice']);
        Country::create(['code'=>'BEN','name'=>	'Benín']);
        Country::create(['code'=>'BMU','name'=>	'Bermudas']);
        Country::create(['code'=>'BLR','name'=>	'Bielorrusia']);
        Country::create(['code'=>'MMR','name'=>	'Myanmar']);
        Country::create(['code'=>'BOL','name'=>	'Bolivia, Estado Plurinacional de']);
        Country::create(['code'=>'BIH','name'=>	'Bosnia y Herzegovina']);
        Country::create(['code'=>'BWA','name'=>	'Botsuana']);
        Country::create(['code'=>'BRA','name'=>	'Brasil']);
        Country::create(['code'=>'BRN','name'=>	'Brunéi Darussalam']);
        Country::create(['code'=>'BGR','name'=>	'Bulgaria']);
        Country::create(['code'=>'BFA','name'=>	'Burkina Faso']);
        Country::create(['code'=>'BDI','name'=>	'Burundi']);
        Country::create(['code'=>'BTN','name'=>	'Bután']);
        Country::create(['code'=>'CPV','name'=>	'Cabo Verde']);
        Country::create(['code'=>'KHM','name'=>	'Camboya']);
        Country::create(['code'=>'CMR','name'=>	'Camerún']);
        Country::create(['code'=>'CAN','name'=>	'Canadá']);
        Country::create(['code'=>'QAT','name'=>	'Catar']);
        Country::create(['code'=>'BES','name'=>	'Bonaire, San Eustaquio y Saba']);
        Country::create(['code'=>'TCD','name'=>	'Chad']);
        Country::create(['code'=>'CHL','name'=>	'Chile']);
        Country::create(['code'=>'CHN','name'=>	'China']);
        Country::create(['code'=>'CYP','name'=>	'Chipre']);
        Country::create(['code'=>'COL','name'=>	'Colombia']);
        Country::create(['code'=>'COM','name'=>	'Comoras']);
        Country::create(['code'=>'PRK','name'=>	'Corea (la República Democrática Popular de)']);
        Country::create(['code'=>'KOR','name'=>	'Corea (la República de)']);
        Country::create(['code'=>'CIV','name'=>	'Côte d\'Ivoire']);
        Country::create(['code'=>'CRI','name'=>	'Costa Rica']);
        Country::create(['code'=>'HRV','name'=>	'Croacia']);
        Country::create(['code'=>'CUB','name'=>	'Cuba']);
        Country::create(['code'=>'CUW','name'=>	'Curaçao']);
        Country::create(['code'=>'DNK','name'=>	'Dinamarca']);
        Country::create(['code'=>'DMA','name'=>	'Dominica']);
        Country::create(['code'=>'ECU','name'=>	'Ecuador']);
        Country::create(['code'=>'EGY','name'=>	'Egipto']);
        Country::create(['code'=>'SLV','name'=>	'El Salvador']);
        Country::create(['code'=>'ARE','name'=>	'Emiratos Árabes Unidos (Los)']);
        Country::create(['code'=>'ERI','name'=>	'Eritrea']);
        Country::create(['code'=>'SVK','name'=>	'Eslovaquia']);
        Country::create(['code'=>'SVN','name'=>	'Eslovenia']);
        Country::create(['code'=>'ESP','name'=>	'España']);
        Country::create(['code'=>'USA','name'=>	'Estados Unidos (los)']);
        Country::create(['code'=>'EST','name'=>	'Estonia']);
        Country::create(['code'=>'ETH','name'=>	'Etiopía']);
        Country::create(['code'=>'PHL','name'=>	'Filipinas (las)']);
        Country::create(['code'=>'FIN','name'=>	'Finlandia']);
        Country::create(['code'=>'FJI','name'=>	'Fiyi']);
        Country::create(['code'=>'FRA','name'=>	'Francia']);
        Country::create(['code'=>'GAB','name'=>	'Gabón']);
        Country::create(['code'=>'GMB','name'=>	'Gambia (La)']);
        Country::create(['code'=>'GEO','name'=>	'Georgia']);
        Country::create(['code'=>'GHA','name'=>	'Ghana']);
        Country::create(['code'=>'GIB','name'=>	'Gibraltar']);
        Country::create(['code'=>'GRD','name'=>	'Granada']);
        Country::create(['code'=>'GRC','name'=>	'Grecia']);
        Country::create(['code'=>'GRL','name'=>	'Groenlandia']);
        Country::create(['code'=>'GLP','name'=>	'Guadalupe']);
        Country::create(['code'=>'GUM','name'=>	'Guam']);
        Country::create(['code'=>'GTM','name'=>	'Guatemala']);
        Country::create(['code'=>'GUF','name'=>	'Guayana Francesa']);
        Country::create(['code'=>'GGY','name'=>	'Guernsey']);
        Country::create(['code'=>'GIN','name'=>	'Guinea']);
        Country::create(['code'=>'GNB','name'=>	'Guinea-Bisáu']);
        Country::create(['code'=>'GNQ','name'=>	'Guinea Ecuatorial']);
        Country::create(['code'=>'GUY','name'=>	'Guyana']);
        Country::create(['code'=>'HTI','name'=>	'Haití']);
        Country::create(['code'=>'HND','name'=>	'Honduras']);
        Country::create(['code'=>'HKG','name'=>	'Hong Kong']);
        Country::create(['code'=>'HUN','name'=>	'Hungría']);
        Country::create(['code'=>'IND','name'=>	'India']);
        Country::create(['code'=>'IDN','name'=>	'Indonesia']);
        Country::create(['code'=>'IRQ','name'=>	'Irak']);
        Country::create(['code'=>'IRN','name'=>	'Irán (la República Islámica de)']);
        Country::create(['code'=>'IRL','name'=>	'Irlanda']);
        Country::create(['code'=>'BVT','name'=>	'Isla Bouvet']);
        Country::create(['code'=>'IMN','name'=>	'Isla de Man']);
        Country::create(['code'=>'CXR','name'=>	'Isla de Navidad']);
        Country::create(['code'=>'NFK','name'=>	'Isla Norfolk']);
        Country::create(['code'=>'ISL','name'=>	'Islandia']);
        Country::create(['code'=>'CYM','name'=>	'Islas Caimán (las)']);
        Country::create(['code'=>'CCK','name'=>	'Islas Cocos (Keeling)']);
        Country::create(['code'=>'COK','name'=>	'Islas Cook (las)']);
        Country::create(['code'=>'FRO','name'=>	'Islas Feroe (las)']);
        Country::create(['code'=>'SGS','name'=>	'Georgia del sur y las islas sandwich del sur']);
        Country::create(['code'=>'HMD','name'=>	'Isla Heard e Islas McDonald']);
        Country::create(['code'=>'FLK','name'=>	'Islas Malvinas [Falkland] (las)']);
        Country::create(['code'=>'MNP','name'=>	'Islas Marianas del Norte (las)']);
        Country::create(['code'=>'MHL','name'=>	'Islas Marshall (las)']);
        Country::create(['code'=>'PCN','name'=>	'Pitcairn']);
        Country::create(['code'=>'SLB','name'=>	'Islas Salomón (las)']);
        Country::create(['code'=>'TCA','name'=>	'Islas Turcas y Caicos (las)']);
        Country::create(['code'=>'UMI','name'=>	'Islas de Ultramar Menores de Estados Unidos (las)']);
        Country::create(['code'=>'VGB','name'=>	'Islas Vírgenes (Británicas)']);
        Country::create(['code'=>'VIR','name'=>	'Islas Vírgenes (EE.UU.)']);
        Country::create(['code'=>'ISR','name'=>	'Israel']);
        Country::create(['code'=>'ITA','name'=>	'Italia']);
        Country::create(['code'=>'JAM','name'=>	'Jamaica']);
        Country::create(['code'=>'JPN','name'=>	'Japón']);
        Country::create(['code'=>'JEY','name'=>	'Jersey']);
        Country::create(['code'=>'JOR','name'=>	'Jordania']);
        Country::create(['code'=>'KAZ','name'=>	'Kazajistán']);
        Country::create(['code'=>'KEN','name'=>	'Kenia']);
        Country::create(['code'=>'KGZ','name'=>	'Kirguistán']);
        Country::create(['code'=>'KIR','name'=>	'Kiribati']);
        Country::create(['code'=>'KWT','name'=>	'Kuwait']);
        Country::create(['code'=>'LAO','name'=>	'Lao, (la) República Democrática Popular']);
        Country::create(['code'=>'LSO','name'=>	'Lesoto']);
        Country::create(['code'=>'LVA','name'=>	'Letonia']);
        Country::create(['code'=>'LBN','name'=>	'Líbano']);
        Country::create(['code'=>'LBR','name'=>	'Liberia']);
        Country::create(['code'=>'LBY','name'=>	'Libia']);
        Country::create(['code'=>'LIE','name'=>	'Liechtenstein']);
        Country::create(['code'=>'LTU','name'=>	'Lituania']);
        Country::create(['code'=>'LUX','name'=>	'Luxemburgo']);
        Country::create(['code'=>'MAC','name'=>	'Macao']);
        Country::create(['code'=>'MDG','name'=>	'Madagascar']);
        Country::create(['code'=>'MYS','name'=>	'Malasia']);
        Country::create(['code'=>'MWI','name'=>	'Malaui']);
        Country::create(['code'=>'MDV','name'=>	'Maldivas']);
        Country::create(['code'=>'MLI','name'=>	'Malí']);
        Country::create(['code'=>'MLT','name'=>	'Malta']);
        Country::create(['code'=>'MAR','name'=>	'Marruecos']);
        Country::create(['code'=>'MTQ','name'=>	'Martinica']);
        Country::create(['code'=>'MUS','name'=>	'Mauricio']);
        Country::create(['code'=>'MRT','name'=>	'Mauritania']);
        Country::create(['code'=>'MYT','name'=>	'Mayotte']);
        Country::create(['code'=>'MEX','name'=>	'México']);
        Country::create(['code'=>'FSM','name'=>	'Micronesia (los Estados Federados de)']);
        Country::create(['code'=>'MDA','name'=>	'Moldavia (la República de)']);
        Country::create(['code'=>'MCO','name'=>	'Mónaco']);
        Country::create(['code'=>'MNG','name'=>	'Mongolia']);
        Country::create(['code'=>'MNE','name'=>	'Montenegro']);
        Country::create(['code'=>'MSR','name'=>	'Montserrat']);
        Country::create(['code'=>'MOZ','name'=>	'Mozambique']);
        Country::create(['code'=>'NAM','name'=>	'Namibia']);
        Country::create(['code'=>'NRU','name'=>	'Nauru']);
        Country::create(['code'=>'NPL','name'=>	'Nepal']);
        Country::create(['code'=>'NIC','name'=>	'Nicaragua']);
        Country::create(['code'=>'NER','name'=>	'Níger (el)']);
        Country::create(['code'=>'NGA','name'=>	'Nigeria']);
        Country::create(['code'=>'NIU','name'=>	'Niue']);
        Country::create(['code'=>'NOR','name'=>	'Noruega']);
        Country::create(['code'=>'NCL','name'=>	'Nueva Caledonia']);
        Country::create(['code'=>'NZL','name'=>	'Nueva Zelanda']);
        Country::create(['code'=>'OMN','name'=>	'Omán']);
        Country::create(['code'=>'NLD','name'=>	'Países Bajos (los)']);
        Country::create(['code'=>'PAK','name'=>	'Pakistán']);
        Country::create(['code'=>'PLW','name'=>	'Palaos']);
        Country::create(['code'=>'PSE','name'=>	'Palestina, Estado de']);
        Country::create(['code'=>'PAN','name'=>	'Panamá']);
        Country::create(['code'=>'PNG','name'=>	'Papúa Nueva Guinea']);
        Country::create(['code'=>'PRY','name'=>	'Paraguay']);
        Country::create(['code'=>'PER','name'=>	'Perú']);
        Country::create(['code'=>'PYF','name'=>	'Polinesia Francesa']);
        Country::create(['code'=>'POL','name'=>	'Polonia']);
        Country::create(['code'=>'PRT','name'=>	'Portugal']);
        Country::create(['code'=>'PRI','name'=>	'Puerto Rico']);
        Country::create(['code'=>'GBR','name'=>	'Reino Unido (el)']);
        Country::create(['code'=>'CAF','name'=>	'República Centroafricana (la)']);
        Country::create(['code'=>'CZE','name'=>	'República Checa (la)']);
        Country::create(['code'=>'MKD','name'=>	'Macedonia (la antigua República Yugoslava de)']);
        Country::create(['code'=>'COG','name'=>	'Congo']);
        Country::create(['code'=>'COD','name'=>	'Congo (la República Democrática del)']);
        Country::create(['code'=>'DOM','name'=>	'República Dominicana (la)']);
        Country::create(['code'=>'REU','name'=>	'Reunión']);
        Country::create(['code'=>'RWA','name'=>	'Ruanda']);
        Country::create(['code'=>'ROU','name'=>	'Rumania']);
        Country::create(['code'=>'RUS','name'=>	'Rusia, (la) Federación de']);
        Country::create(['code'=>'ESH','name'=>	'Sahara Occidental']);
        Country::create(['code'=>'WSM','name'=>	'Samoa']);
        Country::create(['code'=>'ASM','name'=>	'Samoa Americana']);
        Country::create(['code'=>'BLM','name'=>	'San Bartolomé']);
        Country::create(['code'=>'KNA','name'=>	'San Cristóbal y Nieves']);
        Country::create(['code'=>'SMR','name'=>	'San Marino']);
        Country::create(['code'=>'MAF','name'=>	'San Martín (parte francesa)']);
        Country::create(['code'=>'SPM','name'=>	'San Pedro y Miquelón']);
        Country::create(['code'=>'VCT','name'=>	'San Vicente y las Granadinas']);
        Country::create(['code'=>'SHN','name'=>	'Santa Helena, Ascensión y Tristán de Acuña']);
        Country::create(['code'=>'LCA','name'=>	'Santa Lucía']);
        Country::create(['code'=>'STP','name'=>	'Santo Tomé y Príncipe']);
        Country::create(['code'=>'SEN','name'=>	'Senegal']);
        Country::create(['code'=>'SRB','name'=>	'Serbia']);
        Country::create(['code'=>'SYC','name'=>	'Seychelles']);
        Country::create(['code'=>'SLE','name'=>	'Sierra leona']);
        Country::create(['code'=>'SGP','name'=>	'Singapur']);
        Country::create(['code'=>'SXM','name'=>	'Sint Maarten (parte holandesa)']);
        Country::create(['code'=>'SYR','name'=>	'Siria, (la) República Árabe']);
        Country::create(['code'=>'SOM','name'=>	'Somalia']);
        Country::create(['code'=>'LKA','name'=>	'Sri Lanka']);
        Country::create(['code'=>'SWZ','name'=>	'Suazilandia']);
        Country::create(['code'=>'ZAF','name'=>	'Sudáfrica']);
        Country::create(['code'=>'SDN','name'=>	'Sudán (el)']);
        Country::create(['code'=>'SSD','name'=>	'Sudán del Sur']);
        Country::create(['code'=>'SWE','name'=>	'Suecia']);
        Country::create(['code'=>'CHE','name'=>	'Suiza']);
        Country::create(['code'=>'SUR','name'=>	'Surinam']);
        Country::create(['code'=>'SJM','name'=>	'Svalbard y Jan Mayen']);
        Country::create(['code'=>'THA','name'=>	'Tailandia']);
        Country::create(['code'=>'TWN','name'=>	'Taiwán (Provincia de China)']);
        Country::create(['code'=>'TZA','name'=>	'Tanzania, República Unida de']);
        Country::create(['code'=>'TJK','name'=>	'Tayikistán']);
        Country::create(['code'=>'IOT','name'=>	'Territorio Británico del Océano Índico (el)']);
        Country::create(['code'=>'ATF','name'=>	'Territorios Australes Franceses (los)']);
        Country::create(['code'=>'TLS','name'=>	'Timor-Leste']);
        Country::create(['code'=>'TGO','name'=>	'Togo']);
        Country::create(['code'=>'TKL','name'=>	'Tokelau']);
        Country::create(['code'=>'TON','name'=>	'Tonga']);
        Country::create(['code'=>'TTO','name'=>	'Trinidad y Tobago']);
        Country::create(['code'=>'TUN','name'=>	'Túnez']);
        Country::create(['code'=>'TKM','name'=>	'Turkmenistán']);
        Country::create(['code'=>'TUR','name'=>	'Turquía']);
        Country::create(['code'=>'TUV','name'=>	'Tuvalu']);
        Country::create(['code'=>'UKR','name'=>	'Ucrania']);
        Country::create(['code'=>'UGA','name'=>	'Uganda']);
        Country::create(['code'=>'URY','name'=>	'Uruguay']);
        Country::create(['code'=>'UZB','name'=>	'Uzbekistán']);
        Country::create(['code'=>'VUT','name'=>	'Vanuatu']);
        Country::create(['code'=>'VAT','name'=>	'Santa Sede[Estado de la Ciudad del Vaticano] (la)']);
        Country::create(['code'=>'VEN','name'=>	'Venezuela, República Bolivariana de']);
        Country::create(['code'=>'VNM','name'=>	'Viet Nam']);
        Country::create(['code'=>'WLF','name'=>	'Wallis y Futuna']);
        Country::create(['code'=>'YEM','name'=>	'Yemen']);
        Country::create(['code'=>'DJI','name'=>	'Yibuti']);
        Country::create(['code'=>'ZMB','name'=>	'Zambia']);
        Country::create(['code'=>'ZWE','name'=>	'Zimbabue']);
        Country::create(['code'=>'ZZZ','name'=>	'Países no declarados']);
    }
}
